### ISSUE TITLE
Program mutator - Mutant équivalent

### ISSUE THREAD

**Issue by waberto** [ismaelrami/VV_MutationTesting#19]
Comment détecter des "equivalent mutant": En effet  la mutation de > par >= ne change pas l'état du programme. Pourriez vous nous donnez une piste ?

**Comment by nharrand** [comment]
Le plus simple c'est contourner le problème en utilisant des mutations dont à confiance dans le fait qu'elles introduisent des comportements différent:

Ex: (Il y avait une typo dans le sujet)
| Original operator | Replaced by |
|-------------------|-------------|
|        <                  |     >=         |
|        >                  |     <=         |
|        <=               |      >           |
|        >=               |      <           |

Maintenant, si vous voulez creuser, vous pouvez instrumenter le code pour voir si l'execution du mutant est différente de l'original.

**Comment by nharrand** [comment]
Je suis allé un peu vite dans ma réponse précédente la table de remplacement de l'énoncé ne crée pas des mutant équivalents dans l'absolue (parfois si, mais pas dans le cas général), si > remplacé par >= ne casse pas les tests c'est soit que le projet est mal testé, soit que la spec est plus large que l'implémentation. Cela dit les deux table (la précédente et celle-ci) produisent des mutants qui doivent être tué par les tests.
