### ISSUE TITLE
Test du projet commons-lang

### ISSUE THREAD

**Issue by ismaelrami** [ismaelrami/VV_MutationTesting#21]
Les projets testés peuvent avoir des boucles infinies ? si oui c'est à nous de les détectés ?

**Comment by ismaelrami** [comment]
![capture du 2017-12-05 17-57-51](https://user-images.githubusercontent.com/8472655/33619658-17b6682a-d9e6-11e7-97b3-5f90913f9654.png)

**Comment by nharrand** [comment]
Les mutants crées peuvent tout à fait donner lieu à une boucle infini. (Ce qui ici déclanche un débordement mémoire)

Vous pouvez mettre un time out aux tests et considérer que s'il est dépassé les tests ont échoué et le mutant est donc tué.
