### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by nharrand** [ismaelrami/VV_MutationTesting#23]
- [x] Le projet se lance depuis un terminal.
- [x] Le projet implémente 4 opérateurs.
- [x] Le projet produit un rapport lisible.

- [x] Couverture des tests quasi nulle (Donc pas possible de vous fournir un feedback sur les tests)
- [x] Pas encore de rapport
- [x] Pas d'extention

**Comment by ismaelrami** [comment]
Pouvez vous être précis sur l'aspect extention

**Comment by nharrand** [comment]
Je fais référence à cette partie du sujet:

"
## Additional requirements

While meeting the minimal requirements will only give you an average grade, you are expected to put additional thought on tests such as using a continuous integration system (travis or jenkins, or implement additional features (visualization of results, GUI, additional core functionalities).
"

**Comment by ismaelrami** [comment]
Effectivement nous utilisons travis, à la racine du projet vous pouvez constater la présence du fichier .travis.yml

**Comment by nharrand** [comment]
En effet, autant pour moi.

Cela dit, ce serait pas mal si vous rajoutiez une feature ou deux.

**Comment by ismaelrami** [comment]
oui nous pensons fournir le rapport sous forme html (GUI)

**Comment by nharrand** [comment]
Parfait.

**Comment by ismaelrami** [comment]
3 derniers points réalisés
