### ISSUE TITLE
Erreur de configuration dans le fichier application.properties

### ISSUE THREAD

**Issue by rsoumail** [ismaelrami/VV_MutationTesting#24]
Bonjour monsieur, il un problème de configiration par rapport à notre projet, il faut spécifier votre maven home dans le fichier application.properties se trouvant dans le dossier resources pour que le mvn test et mvn package fonctionne sur le projet mutator (cela est du au fait qu'on ne passe pas de fichier en parametre pour le mvn package qui effectue un mvn test avant). Je viens juste de m'en rendre compte que nous n'avions pas spécifier cela dans le readme. En espérant que vous n'aviez pas encore tester notre projet. Bien à vous.

**Comment by ismaelrami** [comment]
Cela est du au fait qu'il fallait préciser le maven home pour travis-ci qui était différent du notre. Merci pour votre compréhension
